from enum import IntEnum
from handlers import *

class OpCode(IntEnum):
    SERVER_PING = 10
    E_DEVICE_SYNC = 11
    OPEN_CLOSE = 13
    SENSOR_DATA = 14
    BORROWEDITEMS_INFO = 20
    BORROWEDITEMS_REQUEST = 21
    AVAILABLE_ITEMS = 22
    BORROW_ITEM = 23
    BORROWED_ITEM_CHANGE = 24
    AC = 30
    AC_ONOFF = 31
    AC_SWINGFAN = 32
    AC_UPTEMP = 33
    AC_DOWNTEMP = 34
    AUTH = 40
    LAYOUT_REQUEST = 41
    USERS_REQUEST_ADMIN = 42
    E_DEVICES_REQUEST_ADMIN = 43
    ITEMS_REQUEST_ADMIN = 44
    BORROWEDITEMS_REQUEST_ADMIN = 45
    ACCESS_REQUEST_ADMIN = 46
    ADD_USER_ADMIN = 50
    MODIFY_USER_ADMIN = 51
    DELETE_USER_ADMIN = 52
    ADD_ITEM_ADMIN = 53
    MODIFY_ITEM_ADMIN = 54
    DELETE_ITEM_ADMIN = 55
    ADD_ANNOUNCEMENT_ADMIN = 56
    MODIFY_ANNOUNCEMENT_ADMIN = 57
    DELETE_ANNOUNCEMENT_ADMIN = 58


OP_HANDLERS = {
    OpCode.SERVER_PING: handle_SERVER_PING,
    OpCode.E_DEVICE_SYNC: handle_E_DEVICE_SYNC,
    OpCode.OPEN_CLOSE: handle_OPEN_CLOSE,
    OpCode.SENSOR_DATA: handle_WEATHER_UPDATE,
    OpCode.BORROWEDITEMS_INFO: handle_INFO_BORROWEDITEMS,
    OpCode.BORROWEDITEMS_REQUEST: handle_BORROWEDITEMS_REQUEST,
    OpCode.AVAILABLE_ITEMS: handle_AVAILABLE_ITEMS,
    OpCode.BORROW_ITEM: handle_BORROW_ITEM,
    OpCode.BORROWED_ITEM_CHANGE: handle_BORROWEDITEM_CHANGE,
    OpCode.AC: handle_AC,
    OpCode.AUTH: handle_AUTH,
    OpCode.LAYOUT_REQUEST: handle_LAYOUT_REQUEST,
    OpCode.USERS_REQUEST_ADMIN: handle_USERS_REQUEST_ADMIN,
    OpCode.E_DEVICES_REQUEST_ADMIN: handle_E_DEVICES_REQUEST_ADMIN,
    OpCode.ITEMS_REQUEST_ADMIN: handle_ITEMS_REQUEST_ADMIN,
    OpCode.BORROWEDITEMS_REQUEST_ADMIN: handle_BORROWEDITEMS_REQUEST_ADMIN,
    OpCode.ACCESS_REQUEST_ADMIN: handle_ACCESS_REQUEST_ADMIN,
    OpCode.ADD_USER_ADMIN: handle_ADD_USER_ADMIN,
    OpCode.MODIFY_USER_ADMIN: handle_MODIFY_USER_ADMIN,
    OpCode.DELETE_USER_ADMIN: handle_DELETE_USER_ADMIN,
    OpCode.ADD_ITEM_ADMIN: handle_ADD_ITEM_ADMIN,
    OpCode.MODIFY_ITEM_ADMIN: handle_MODIFY_ITEM_ADMIN,
    OpCode.DELETE_ITEM_ADMIN: handle_DELETE_ITEM_ADMIN,
    OpCode.ADD_ANNOUNCEMENT_ADMIN: handle_ADD_ANNOUNCEMENT_ADMIN,
    OpCode.MODIFY_ANNOUNCEMENT_ADMIN: handle_MODIFY_ANNOUNCEMENT_ADMIN,
    OpCode.DELETE_ANNOUNCEMENT_ADMIN: handle_DELETE_ANNOUNCEMENT_ADMIN
}
